In [1]:
import torch

In [4]:
torch.__version__

'2.5.1'

In [7]:
if torch.cuda.is_available():
    print("CUDA available:", torch.cuda.is_available())
    print("Device count:", torch.cuda.device_count())
    print("Device:", torch.cuda.get_device_name(0))
    print("Current device index:", torch.cuda.current_device())
else:
    print("CUDA is not available.")

CUDA is not available.


In [27]:
# x 초기화
x = torch.empty(4,2)
# rand
x = torch.randn(4,2)
x
# data type(dtype) long, zero tensor
x = torch.zeros((4, 2), dtype=torch.long)
x
# 입력 값
x = torch.tensor([3, 2.3])
x

x = torch.ones((2, 4), dtype=torch.double)
x
# x와 같은 크기, float 타입, 무작위 채워진 텐서
x = torch.randn_like(x, dtype=float)
x
# x 크기
x.size()

torch.Size([2, 4])

In [29]:
ft = torch.FloatTensor([1, 2, 3])
print(ft)
print(ft.dtype)
torch.tensor([1, 2, 3], dtype=float)

tensor([1., 2., 3.])
torch.float32


In [47]:
x = torch.tensor([1, 2, 3], dtype=float)
x[0].item()

1.0

In [49]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

In [50]:
y = torch.ones_like(x, device=device)

In [53]:
y

tensor([1., 1., 1.], dtype=torch.float64)

## 다차원 텐서

In [58]:
t0 = torch.tensor(0)
print(t0.dim())
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


In [59]:
t1 = torch.tensor([1, 2, 3])
print(t1.dim())
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


In [61]:
t2 = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(t2.dim())
print(t2.shape)
print(t2)

2
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [63]:
t3 = torch.tensor([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],
                  [[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],
                  [[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]]])
print(t3.dim())
print(t3.shape)
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


## 텐서의 연산(Operation)

In [70]:
import math

a = torch.rand(1, 2) * 2 -1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

tensor([[-0.1950,  0.6613]])
tensor([[0.1950, 0.6613]])
tensor([[-0., 1.]])
tensor([[-1.,  0.]])
tensor([[-0.1950,  0.5000]])


In [72]:
print(a)
print(torch.min(a))
print(torch.max(a))
print(torch.mean(a))
print(torch.std(a))
print(torch.prod(a))
print(torch.unique(torch.tensor([1, 2, 3, 1, 2, 2])))

tensor([[-0.1950,  0.6613]])
tensor(-0.1950)
tensor(0.6613)
tensor(0.2331)
tensor(0.6055)
tensor(-0.1290)
tensor([1, 2, 3])


In [88]:
x = torch.rand(2, 2)
print(x)
print(x.max(dim=0))
print(x.max(dim=1))

tensor([[0.4107, 0.2034],
        [0.8031, 0.0360]])
torch.return_types.max(
values=tensor([0.8031, 0.2034]),
indices=tensor([1, 0]))
torch.return_types.max(
values=tensor([0.4107, 0.8031]),
indices=tensor([0, 0]))


In [89]:
x = torch.rand(2, 2)
print(x)
print(x.min(dim=0))
print(x.min(dim=1))

tensor([[0.1620, 0.8768],
        [0.6486, 0.7011]])
torch.return_types.min(
values=tensor([0.1620, 0.7011]),
indices=tensor([0, 1]))
torch.return_types.min(
values=tensor([0.1620, 0.6486]),
indices=tensor([0, 0]))


In [90]:
x = torch.rand(2,2)
print(x)
y = torch.rand(2,2)
print(y)

tensor([[0.8464, 0.4400],
        [0.6405, 0.6339]])
tensor([[0.8367, 0.4720],
        [0.5225, 0.0527]])


In [95]:
print(torch.add(x, y))

tensor([[1.6831, 0.9120],
        [1.1631, 0.6866]])


In [97]:
result = torch.empty(2, 4)
torch.add(x, y, out = result)
result

/var/folders/52/0nmqjhrd7718bmppzfvgp0r40000gn/T/ipykernel_12682/1389944596.py:2: UserWarning: An output with one or more elements was resized since it had shape [2, 4], which does not match the required output shape [2, 2]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at /private/var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_35qhz7nt_q/croot/libtorch_1738269285820/work/aten/src/ATen/native/Resize.cpp:35.)
  torch.add(x, y, out = result)


tensor([[1.6831, 0.9120],
        [1.1631, 0.6866]])

In [98]:
print(x)
print(y)
y.add_(x)
print(y)

tensor([[0.8464, 0.4400],
        [0.6405, 0.6339]])
tensor([[0.8367, 0.4720],
        [0.5225, 0.0527]])
tensor([[1.6831, 0.9120],
        [1.1631, 0.6866]])


In [100]:
print(x)
print(y)
print(torch.matmul(x, y))
z = torch.mm(x, y)
print(z)

tensor([[0.8464, 0.4400],
        [0.6405, 0.6339]])
tensor([[1.6831, 0.9120],
        [1.1631, 0.6866]])
tensor([[1.9362, 1.0740],
        [1.8153, 1.0194]])
tensor([[1.9362, 1.0740],
        [1.8153, 1.0194]])


## 텐서의 조작(Manipulations)

In [108]:
x = torch.Tensor([[1, 2],
              [3, 4]])
print(x)
print(x[0, 0])
print(x[0, 1])
print(x[1, 0])
print(x[1, 1])

print(x[:, 0])
print(x[:, 1])

print(x[0, :])
print(x[1, :])

tensor([[1., 2.],
        [3., 4.]])
tensor(1.)
tensor(2.)
tensor(3.)
tensor(4.)
tensor([1., 3.])
tensor([2., 4.])
tensor([1., 2.])
tensor([3., 4.])


In [117]:
x = torch.randn(4, 5)
print(x)
y = x.view(20)
print(y)
z = x.view(5, -1)
print(z)

tensor([[-0.7141,  0.1628,  0.2524,  1.2652,  1.9504],
        [ 0.7660, -0.2428, -0.9563,  1.2390,  0.2883],
        [-0.5817,  0.1911,  0.1455, -0.0280,  0.8411],
        [-1.7041,  0.0440,  0.8163, -1.5161,  0.9038]])
tensor([-0.7141,  0.1628,  0.2524,  1.2652,  1.9504,  0.7660, -0.2428, -0.9563,
         1.2390,  0.2883, -0.5817,  0.1911,  0.1455, -0.0280,  0.8411, -1.7041,
         0.0440,  0.8163, -1.5161,  0.9038])
tensor([[-0.7141,  0.1628,  0.2524,  1.2652],
        [ 1.9504,  0.7660, -0.2428, -0.9563],
        [ 1.2390,  0.2883, -0.5817,  0.1911],
        [ 0.1455, -0.0280,  0.8411, -1.7041],
        [ 0.0440,  0.8163, -1.5161,  0.9038]])


In [120]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([0.8968])
0.896837055683136
torch.float32


In [123]:
tensor = torch.rand(1, 3, 3)
print(tensor)
print(tensor.shape)

tensor([[[0.0303, 0.8243, 0.4117],
         [0.0234, 0.4019, 0.3901],
         [0.8884, 0.9278, 0.7924]]])
torch.Size([1, 3, 3])


In [125]:
t = tensor.squeeze()
print(t)
print(t.shape)

tensor([[0.0303, 0.8243, 0.4117],
        [0.0234, 0.4019, 0.3901],
        [0.8884, 0.9278, 0.7924]])
torch.Size([3, 3])


In [126]:
t = torch.rand(3, 3)
print(t)
print(t.shape)

tensor([[0.2048, 0.5273, 0.4215],
        [0.1944, 0.4101, 0.0502],
        [0.5792, 0.7643, 0.2636]])
torch.Size([3, 3])


In [152]:
tensor = t.unsqueeze(dim=2)

In [153]:
print(tensor.shape)
tensor

torch.Size([3, 3, 1])


tensor([[[0.2048],
         [0.5273],
         [0.4215]],

        [[0.1944],
         [0.4101],
         [0.0502]],

        [[0.5792],
         [0.7643],
         [0.2636]]])

In [158]:
x = torch.FloatTensor([1, 4])
print(x)
y = torch.FloatTensor([2, 5])
print(y)
z = torch.FloatTensor([3, 6])
print(z)
print(torch.stack([x, y, z]))

tensor([1., 4.])
tensor([2., 5.])
tensor([3., 6.])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [160]:
a = torch.randn(1, 3, 3)
print(a)
b = torch.randn(1, 3, 3)
print(b)
c = torch.cat((a, b), dim=0)
print(c)
print(c.size())

tensor([[[ 0.5629, -0.7608,  1.1164],
         [-0.6325, -0.9733,  0.1154],
         [ 1.4367,  0.5077, -0.7742]]])
tensor([[[-0.7302,  0.0337,  1.2764],
         [-0.7177, -0.5939,  0.9219],
         [-0.8376, -0.1871, -1.0239]]])
tensor([[[ 0.5629, -0.7608,  1.1164],
         [-0.6325, -0.9733,  0.1154],
         [ 1.4367,  0.5077, -0.7742]],

        [[-0.7302,  0.0337,  1.2764],
         [-0.7177, -0.5939,  0.9219],
         [-0.8376, -0.1871, -1.0239]]])
torch.Size([2, 3, 3])


In [161]:
c = torch.cat((a, b), dim=1)
print(c)
print(c.size())

tensor([[[ 0.5629, -0.7608,  1.1164],
         [-0.6325, -0.9733,  0.1154],
         [ 1.4367,  0.5077, -0.7742],
         [-0.7302,  0.0337,  1.2764],
         [-0.7177, -0.5939,  0.9219],
         [-0.8376, -0.1871, -1.0239]]])
torch.Size([1, 6, 3])


In [178]:
tensor = torch.rand(3, 6)
print(tensor)

t1, t2 = torch.chunk(tensor, 2, dim=1)
print(t1)
print(t2)
# print(t3)

tensor([[0.8162, 0.3021, 0.2822, 0.7667, 0.5248, 0.7527],
        [0.1422, 0.0046, 0.6323, 0.4470, 0.2412, 0.3913],
        [0.8458, 0.2562, 0.3756, 0.9871, 0.9530, 0.3202]])
tensor([[0.8162, 0.3021, 0.2822],
        [0.1422, 0.0046, 0.6323],
        [0.8458, 0.2562, 0.3756]])
tensor([[0.7667, 0.5248, 0.7527],
        [0.4470, 0.2412, 0.3913],
        [0.9871, 0.9530, 0.3202]])
